// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastextract_buffer_cpp
NumericMatrix fastextract_buffer_cpp(NumericMatrix mat, NumericMatrix coords, double x_min, double y_min, double res_x, double res_y, double radius, std::string stat, bool na_rm, std::string window);
RcppExport SEXP _fastfocal_fastextract_buffer_cpp(SEXP matSEXP, SEXP coordsSEXP, SEXP x_minSEXP, SEXP y_minSEXP, SEXP res_xSEXP, SEXP res_ySEXP, SEXP radiusSEXP, SEXP statSEXP, SEXP na_rmSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type y_min(y_minSEXP);
    Rcpp::traits::input_parameter< double >::type res_x(res_xSEXP);
    Rcpp::traits::input_parameter< double >::type res_y(res_ySEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< std::string >::type stat(statSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    Rcpp::traits::input_parameter< std::string >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(fastextract_buffer_cpp(mat, coords, x_min, y_min, res_x, res_y, radius, stat, na_rm, window));
    return rcpp_result_gen;
END_RCPP
}
// fastextract_multi_cpp
NumericMatrix fastextract_multi_cpp(List raster_mats, NumericMatrix coords, NumericVector x_coords, NumericVector y_coords, NumericVector res_x, NumericVector res_y);
RcppExport SEXP _fastfocal_fastextract_multi_cpp(SEXP raster_matsSEXP, SEXP coordsSEXP, SEXP x_coordsSEXP, SEXP y_coordsSEXP, SEXP res_xSEXP, SEXP res_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type raster_mats(raster_matsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_coords(x_coordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_coords(y_coordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res_x(res_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res_y(res_ySEXP);
    rcpp_result_gen = Rcpp::wrap(fastextract_multi_cpp(raster_mats, coords, x_coords, y_coords, res_x, res_y));
    return rcpp_result_gen;
END_RCPP
}
// fastextract_point_cpp
NumericMatrix fastextract_point_cpp(NumericMatrix raster_mat, NumericMatrix coords, NumericVector x_coords, NumericVector y_coords, NumericVector res_x, NumericVector res_y);
RcppExport SEXP _fastfocal_fastextract_point_cpp(SEXP raster_matSEXP, SEXP coordsSEXP, SEXP x_coordsSEXP, SEXP y_coordsSEXP, SEXP res_xSEXP, SEXP res_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type raster_mat(raster_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_coords(x_coordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_coords(y_coordsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res_x(res_xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type res_y(res_ySEXP);
    rcpp_result_gen = Rcpp::wrap(fastextract_point_cpp(raster_mat, coords, x_coords, y_coords, res_x, res_y));
    return rcpp_result_gen;
END_RCPP
}
// fastfocal_cpp
NumericMatrix fastfocal_cpp(NumericMatrix mat, double res_x, double res_y, double radius, std::string stat);
RcppExport SEXP _fastfocal_fastfocal_cpp(SEXP matSEXP, SEXP res_xSEXP, SEXP res_ySEXP, SEXP radiusSEXP, SEXP statSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< double >::type res_x(res_xSEXP);
    Rcpp::traits::input_parameter< double >::type res_y(res_ySEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< std::string >::type stat(statSEXP);
    rcpp_result_gen = Rcpp::wrap(fastfocal_cpp(mat, res_x, res_y, radius, stat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fastfocal_fastextract_buffer_cpp", (DL_FUNC) &_fastfocal_fastextract_buffer_cpp, 10},
    {"_fastfocal_fastextract_multi_cpp", (DL_FUNC) &_fastfocal_fastextract_multi_cpp, 6},
    {"_fastfocal_fastextract_point_cpp", (DL_FUNC) &_fastfocal_fastextract_point_cpp, 6},
    {"_fastfocal_fastfocal_cpp", (DL_FUNC) &_fastfocal_fastfocal_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_fastfocal(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
