# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastextract_buffer_cpp <- function(mat, coords, x_min, y_min, res_x, res_y, radius, stat, na_rm = TRUE, window = "circular") {
    .Call(`_fastfocal_fastextract_buffer_cpp`, mat, coords, x_min, y_min, res_x, res_y, radius, stat, na_rm, window)
}

fastextract_multi_cpp <- function(raster_mats, coords, x_coords, y_coords, res_x, res_y) {
    .Call(`_fastfocal_fastextract_multi_cpp`, raster_mats, coords, x_coords, y_coords, res_x, res_y)
}

fastextract_point_cpp <- function(raster_mat, coords, x_coords, y_coords, res_x, res_y) {
    .Call(`_fastfocal_fastextract_point_cpp`, raster_mat, coords, x_coords, y_coords, res_x, res_y)
}

fastfocal_cpp <- function(mat, res_x, res_y, radius, stat = "mean") {
    .Call(`_fastfocal_fastfocal_cpp`, mat, res_x, res_y, radius, stat)
}

